resources:
  - name:   in1
    type:   GitRepo
    configuration:
      gitProvider:  GitIntegration
      path:         aarvyved/testpipe
      buildOn:
        commit:            true
        pullRequestCreate: true
        pullRequestClose:  true
        releaseCreate:     true
        tagCreate:         true
  - name: in2
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
  - name: in3
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
  - name: in4
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
  - name: in5
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
  - name: out1
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
  - name: out2
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
  - name: out3
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
  - name: out4
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
  - name: out5
    type: GitRepo
    configuration:
      gitProvider: GitIntegration
      path: aarvyved/testpipe
pipelines:
  - name: largePipeline
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: in1
          outputResources:
            - name: out1
        execution:
          onExecute:
            - sleep 10
      - name: step2
        type: Bash
        configuration:
          inputResources:
            - name: out1
        execution:
          onExecute:
            - sleep 10
            - echo "done"
      - name: step3
        type: Bash
        configuration:
          inputResources:
            - name: out1
          outputResources:
            - name: out2
        execution:
          onExecute:
            - sleep 10
            - echo "done"
      - name: step4
        type: Bash
        configuration:
          inputResources:
            - name: out1
          outputResources:
            - name: out3
        execution:
          onExecute:
            - sleep 10
            - echo "done"
      - name: step5
        type: Bash
        configuration:
          inputResources:
            - name: out1
        execution:
          onExecute:
            - sleep 10
            - echo "done"
      - name: step6
        type: Bash
        configuration:
          inputResources:
            - name: out2
        execution:
          onExecute:
            - sleep 10
            - echo "done"
      - name: step7
        type: Bash
        configuration:
          inputResources:
            - name: out3
        execution:
          onExecute:
            - sleep 10
            - echo "done"
      - name: step8
        type: Bash
        configuration:
          inputResources:
            - name: out3
        execution:
          onExecute:
            - sleep 10
            - echo "done"
