resources:
  - name:   res1
    type:   GitRepo
    configuration:
      gitProvider:  GitIntegration
      path:         aarvyved/testpipe
      buildOn:
        commit:            true
        pullRequestCreate: true
        pullRequestClose:  true
        releaseCreate:     true
        tagCreate:         true
pipelines:
  - name: testPipeline
    steps:
      - name: bashTest
        type: Bash
        configuration:
          inputResources:
            - name: res1
        execution:
          onExecute:
            - sleep 10
      - name: bashTest2
        type: Bash
        configuration:
          inputResources:
            - name: git_SANDWICH
        execution:
          onExecute:
            - sleep 10
            - echo "done"
           
