resources:
  - name:   res1
    type:   GitRepo
    configuration:
      gitProvider:  TestIntegration
      path:         aarvyved/testpipe
pipelines:
  - name: testPipeline
    steps:
      - name: bashTest
        type: Bash
        configuration:
          inputResources:
            - name: res1
        execution:
          onExecute:
            - sleep 10
